run:
  build-tags:
  # https://github.com/containers/podman/issues/12548#issuecomment-989053364
  # https://github.com/containers/podman/issues/15733#issuecomment-1242971062
  - remote
  - exclude_graphdriver_btrfs
  - btrfs_noversion
  - exclude_graphdriver_devicemapper
  - containers_image_openpgp
linters:
  enable-all: true
  disable:
  # deprecated
  - exhaustivestruct
  - scopelint
  - ifshort
  - deadcode
  - varcheck
  - structcheck
  - maligned
  - nosnakecase
  - golint
  - interfacer

  # annoying
  - wsl

  # not interested
  - godox
