project_name: telepod
before:
  hooks:
  - go mod tidy
builds:
- binary: telepod
  env:
  - CGO_ENABLED=0
  main: ./cmd/telepod
  goos:
  - linux
  - windows
  - darwin
  flags:
  - -trimpath
  ldflags:
  - -s
  - -w
  - -extldflags
  - -static
  - -X
  - main.version={{.Version}}
  - -X
  - main.commit={{.Commit}}
  - -X
  - main.date={{.Date}}
  - -X
  - main.builtBy=goreleaser
  tags:
  # https://github.com/containers/podman/issues/12548#issuecomment-989053364
  # https://github.com/containers/podman/issues/15733#issuecomment-1242971062
  - remote
  - exclude_graphdriver_btrfs
  - btrfs_noversion
  - exclude_graphdriver_devicemapper
  - containers_image_openpgp
  mod_timestamp: "{{ .CommitTimestamp }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: git
  sort: asc
  # groups:
  # - title: Dependency updates
  #   regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
  #   order: 300
  # - title: 'New Features'
  #   regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
  #   order: 100
  # - title: 'Security updates'
  #   regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
  #   order: 150
  # - title: 'Bug fixes'
  #   regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
  #   order: 200
  # - title: 'Documentation updates'
  #   regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
  #   order: 400
  # - title: 'Build process updates'
  #   regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
  #   order: 400
  # - title: Other work
  #   order: 9999
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
    - Merge pull request
gitea_urls:
  api: https://codeberg.org/api/v1
  download: https://codeberg.org

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
