pipeline:
  lint:
    image: golangci/golangci-lint
    commands:
      # https://github.com/containers/podman/issues/12548#issuecomment-989053364
      # https://github.com/containers/podman/issues/15733#issuecomment-1242971062
      - go build -tags "remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp" ./...
      - golangci-lint run
    when:
      event:  # all events except tag
      - push
      - pull_request
      - deployment
  test:
    image: golang:1.20
    commands:
      - go test -tags "remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp" ./...
    when:
      event:  # all events except tag
      - push
      - pull_request
      - deployment
  release:
    image: goreleaser/goreleaser
    commands:
      - goreleaser release
    secrets:
    - gitea_token
    when:
      event: tag
      tag: v*
