pipeline:
  lint:
    image: golangci/golangci-lint
    commands:
      - golangci-lint run
  test:
    image: golang:1.20
    commands:
      - go test ./...
  release:
    image: goreleaser/goreleaser
    commands:
      - goreleaser release
    secrets:
    - gitea_token
    when:
      event: tag
      tag: v*
